### ISSUE TITLE
Research possible extension for element AustrianPatient.birthplace

### ISSUE THREAD

**Issue by aschuler84** [HL7Austria/hl7-at-fhir-profiles#4]

**Comment by oliver-krauss** [comment]
That one is a little tricky. Here is one: https://www.hl7.org/fhir/extension-birthplace.html 
The problem is that we have the AustrianAddress, meaning that we would have to Extend this Extension with our Extension.

Question is though -> do we want AustrianAddress as Birthplace? What about people born outside the Austrian postal system?

Pro of using this Ext.: Higher international interoperability (do we have a use for this?)
Pro of doing our own: We aren't extending an extension with another extension,

**Comment by oliver-krauss** [comment]
Ok. It looks like we can't do that anyway. We can EITHER use the extension OR we can set it to AustrianAddress. It is not possible to modify the type of an extension.

I did it the AustrianAddressRepresentation way

**Comment by aschuler84** [comment]
Motion Sabutsch/Soulos 9-0-0: use existing AustrianAddressRepresentation for representing birthPlace in favor of hl7 defined birthplace extension.

**Comment by aschuler84** [comment]
TBD Oliver - Merge Request

**Comment by oliver-krauss** [comment]
NOTICE: Since we have not worked on an actual BRANCH for this issue in the dark times before the conventions were defined, I am unable to create a merge request. 

Since we have the "IG meta" issue #21 that also addresses namespaces etc. we will review in that issue

**Comment by oliver-krauss** [comment]
Maybe relevant to also report WHY that motion happened.

Both options support address. Sabutsch noted that no one actually documents a birthplace very well. It is usually "Hospital X" or "Vienna", meaning that granularity is not the issue.

However if we had selected the international extension, the developers in Austria would have to differentiate between "Address" and "at-Address" which makes everything more complicated. 

To have one unified "at-Address" type in the Patient and also to enable more detailed granularity that can actually be processed by at-HealthcareSoftware the motion chose the austrian way.
